export const currencies = [
  //Ethereum tokens
  { value: "ETH (0x123abc...)", label: "Ether" },
  { value: "LINK (0x456def...)", label: "Chainlink" },
  { value: "UNI (0x789ghi...)", label: "Uniswap" },
  { value: "AAVE (0xabc123...)", label: "Aave" },
  { value: "MKR (0xdef456...)", label: "Maker" },
  { value: "COMP (0xghi789...)", label: "Compound" },
  { value: "SUSHI (0x123abc...)", label: "SushiSwap" },
  { value: "SNX (0x456def...)", label: "Synthetix" },
  { value: "YFI (0x789ghi...)", label: "Yearn.finance" },
  { value: "MANA (0xabc123...)", label: "Decentraland" },
  //Polygon tokens
  { value: "MATIC (0xdef456...)", label: "Polygon" },
  { value: "GHST (0xghi789...)", label: "Aavegotchi" },
  { value: "QUICK (0x123abc...)", label: "Quickswap" },
  { value: "POLY (0x456def...)", label: "Polymath" },
  { value: "amTokens (0x789ghi...)", label: "Matic Aave interest bearing tokens" },
  { value: "DG (0xabc123...)", label: "Decentral Games" },
  { value: "TIME (0xdef456...)", label: "Wonderland" },
  { value: "MUST (0xghi789...)", label: "Cometh" },
  { value: "TITAN (0x123abc...)", label: "Iron Finance" },
  { value: "FISH (0x456def...)", label: "PolyCat" },
  //Gnosis Chain tokens 
  { value: "GNO (0x789ghi...)", label: "Gnosis" },
  { value: "PNK (0xabc123...)", label: "Kleros" },
  { value: "REA (0xdef456...)", label: "Realitio" },
  { value: "OMEN (0xghi789...)", label: "Omen" },
  { value: "UMA (0x123abc...)", label: "UMA" },
  { value: "STORJ (0x456def...)", label: "Storj" },
  { value: "RDN (0x789ghi...)", label: "Raiden Network Token" },
  { value: "CGT (0xabc123...)", label: "Gnosis Conditional Tokens" },
  { value: "DXD (0xdef456...)", label: "dxDAO" },
  { value: "SHFT (0xghi789...)", label: "Shyft Network" }
];
