export const currencies = [
  { value: "AE", label: "Aeternity" },
  { value: "BLD", label: "Agoric" },
  { value: "AION", label: "Aion" },
  { value: "AKT", label: "Akash Network" },
  { value: "ALGO", label: "Algorand" },
  { value: "APT", label: "Aptos" },
  { value: "ARETH", label: "Arbitrum" },
  { value: "AGOR", label: "Arbitrum Goerli Testnet" },
  { value: "ARK", label: "Ark" },
  { value: "AYA", label: "Aryacoin" },
  { value: "ETH", label: "Aurora" }, //eth ?
  { value: "AVAX", label: "Avalanche C-Chain" },
  { value: "AVAX", label: "Avalance C-Chain Fuji Testnet" },
  { value: "AVAX", label: "Avalanche X-Chain" },
  { value: "AXL", label: "Axelar" },
  { value: "BAND", label: "BandChain" },
  { value: "BNB", label: "BNB Beacon Chain" }, //not "Binance Coin" ?
  { value: "BTC", label: "Bitcoin" },  
  { value: "BCH", label: "Bitcoin Cash" },
  { value: "BTG", label: "Bitcoin Gold" },
  { value: "BTON", label: "Blockton" },
  { value: "BLZ", label: "Bluzelle" },
  { value: "tBNB", label: "Binance Smart Chain Testnet" },
  { value: "BOBAETH", label: "Boba" },
  { value: "CLO", label: "Callisto Network" },  
  { value: "ADA", label: "Cardano" },
  { value: "CELO", label: "Celo" },
  { value: "ETC", label: "Ethereum Classic" },
  { value: "CMDX", label: "Comdex" },
  { value: "CORE", label: "Coreum" },
  { value: "ATOM", label: "Cosmos" },
  { value: "CRE", label: "Crescent" },
  { value: "CRO", label: "Cronos" }, //
  { value: "CRO", label: "Crypto.org" }, // same symbol ?
  { value: "DASH", label: "Dash" },
  { value: "DCR", label: "Decred" },
  { value: "DGB", label: "DigiByte" },
  { value: "DOGE", label: "Dogecoin" },
  { value: "XEC", label: "eCash" },
  { value: "ELLA", label: "Ellaism" },
  { value: "EGLD", label: "MultiversX" }, //elrond ?
  { value: "EWT", label: "Energy Web Token" },
  { value: "EOS", label: "EOS" },
  { value: "ETHO", label: "Ether-1" },
  { value: "ETH", label: "Ethereum" },
  { value: "ETHW", label: "EthereumPoW" },
  { value: "EVER", label: "Everscale" },
  { value: "EVMOS", label: "Evmos" },
  { value: "FTM", label: "Fantom" },
  { value: "FET", label: "FETCH.AI" },
  { value: "FIL", label: "Filecoin" },
  { value: "FIO", label: "FIO Protocol" },
  { value: "FIRO", label: "Firo" },
  { value: "FSN", label: "Fusion" },
  { value: "gBNB", label: "BNB Greenfield" }, 
  { value: "GO", label: "GoChain" },
  { value: "ETH", label: "Goerli Testnet" },
  { value: "GRS", label: "Groestlcoin" },
  { value: "ONE", label: "Harmony" },
  { value: "HT", label: "Huobi ECO Chain" },
  { value: "HBAR", label: "Hedera" },
  { value: "HOO", label: "Hoo Token" },
  { value: "ICX", label: "ICON" },
  { value: "INJ", label: "Injective" },
  { value: "IOST", label: "IOST" },
  { value: "IOTX", label: "IoTeX" },
  { value: "IOTX", label: "IoTeX Network Mainnet" },
  { value: "IRIS", label: "IRISnet" },
  { value: "JUNO", label: "Juno" },
  { value: "KAVA", label: "Kava" },
  { value: "KAVA", label: "KavaEvm" },
  { value: "KCS", label: "KuCoin Commmunity Chain" },
  { value: "KIN", label: "Kin" },
  { value: "KLAY", label: "klaytn" },
  { value: "KUJI", label: "Kujira" },
  { value: "KSM", label: "Kusama" },
  { value: "LTC", label: "Litecoin" },
  { value: "LOOM", label: "Loom Network" },
  { value: "MARS", label: "Mars Protocol" },
  { value: "MTRG", label: "Meter" },
  { value: "METIS", label: "Metis" },
  { value: "DEV", label: "Moonbase Alpha Testnet" },
  { value: "GLMR", label: "Moonbeam" },
  { value: "MOVR", label: "Moonriver" },
  { value: "XNO", label: "Nano" },
  { value: "CANTO", label: "Native Canto" },
  { value: "EVMOS", label: "Native Evmos" },
  { value: "NEAR", label: "NEAR Protocol" },
  { value: "NAS", label: "Nebulas" },
  { value: "NEO", label: "Neo" },
  { value: "CKB", label: "Nervos Network" },
  { value: "NTRN", label: "Neutron" },
  { value: "NTRN", label: "Neutron Testnet" },
  { value: "NIM", label: "Nimiq" },
  { value: "USDC", label: "Noble" },
  { value: "NULS", label: "NULS" },
  { value: "ROSE", label: "Oasis Network" },
  { value: "OKT", label: "OKX Chain" },
  { value: "OKT", label: "OKXChain Mainnet" },
  { value: "ONT", label: "Ontology" },
  { value: "OETH", label: "Optimistic Ethereum" },
  { value: "ETH", label: "Optimism Goerli Testnet" },
  { value: "OSMO", label: "Osmosis" },
  { value: "XPRT", label: "Persistence" },
  { value: "LAT", label: "PlatON" },
  { value: "POA", label: "POA" },
  { value: "DOT", label: "Polkadot" },
  { value: "MATIC", label: "Polygon" },
  { value: "MATIC", label: "Polygon Mumbai Testnet" },
  { value: "ETH", label: "Polygon zkEVM" },
  { value: "QTUM", label: "Qtum" },
  { value: "QSR", label: "Quasar" },
  { value: "RVN", label: "Ravencoin" },
  { value: "XRP", label: "XRP" }, // not "ripple"
  { value: "RON", label: "Ronin" },
  { value: "SCRT", label: "Secret" },
  { value: "ETH", label: "Sepolia Testnet" },
  { value: "BCH", label: "smartBCH" },
  { value: "BNB", label: "BNB Smart Chain" },
  { value: "SOL", label: "Solana" },
  { value: "SOMM", label: "Sommelier" },
  { value: "STARS", label: "Stargaze" },
  { value: "STEEM", label: "Steem" },
  { value: "XLM", label: "Stellar" },
  { value: "STRD", label: "Stride" },
  { value: "SUI", label: "Sui" },
  { value: "TORI", label: "Teritori" },
  { value: "LUNC", label: "Terra Classic" },
  { value: "LUNA", label: "Terra" },
  { value: "XTZ", label: "Tezos" },
  { value: "tFTM", label: "Fantom Testnet" },
  { value: "THETA", label: "THETA" },
  { value: "RUNE", label: "THORChain" },
  { value: "TT", label: "ThunderCore (TT)" },
  { value: "TOMO", label: "TomoChain" },
  { value: "TON", label: "The Open Network" },
  { value: "TRX", label: "TRON" },
  { value: "UMEE", label: "Umee" },
  { value: "VET", label: "VeChain" },
  { value: "VIA", label: "Viacoin" },
  { value: "WAN", label: "Wanchain" },
  { value: "WAVES", label: "Waves" },
  { value: "xDAI", label: "Gnosis Chain" },
  { value: "XDC", label: "XinFin Network" },
  { value: "ZEC", label: "Zcash" },
  { value: "FLUX", label: "Flux" }, // not "zelcash" ?
  { value: "ZIL", label: "Zilliqa" },
  { value: "ETH", label: "ZkSync Era" },
  // Update crypto-currencies list if needed
  { value: "not_specified", label: "Not Specified" },
  ];
  
  